# latexmk: PDF via pdflatex + biber; output in build/
$pdf_mode = 1;
$out_dir = 'build';
$aux_dir = 'build';
$interaction = 'nonstopmode';
$pdflatex = 'pdflatex -synctex=1 -interaction=nonstopmode %O %S';
$biber = 'biber %O %S';
$bibtex_use = 2;
