from __future__ import annotations

from typing import Any, Protocol


class StudyRepository(Protocol):
    def create_document(self, *, user_id: str, subject_id: str, document_type: str, filename: str, file_size: int, storage_path: str, content_text: str | None = None) -> dict[str, Any]: ...

    def update_document(self, *, user_id: str, document_id: str, updates: dict[str, Any]) -> None: ...

    def list_documents(self, *, user_id: str, subject_id: str | None = None) -> list[dict[str, Any]]: ...

    def delete_document(self, *, user_id: str, document_id: str) -> bool: ...

    def get_document(self, *, user_id: str, document_id: str) -> dict[str, Any] | None: ...

    def save_chunks(self, *, user_id: str, document_id: str, subject_id: str, chunks: list[dict[str, Any]]) -> int: ...

    def list_chunks_for_scope(self, *, user_id: str, scope: str, scope_id: str, limit: int) -> list[dict[str, Any]]: ...

    def save_generated(self, *, user_id: str, scope: str, scope_id: str, content_type: str, content_json: dict[str, Any]) -> dict[str, Any]: ...

    def list_generated(self, *, user_id: str, scope: str, scope_id: str, limit: int) -> list[dict[str, Any]]: ...

    def get_generated(self, *, user_id: str, generated_id: str) -> dict[str, Any] | None: ...

    def update_generated(self, *, user_id: str, generated_id: str, content_json: dict[str, Any]) -> dict[str, Any] | None: ...

    def delete_generated(self, *, user_id: str, generated_id: str) -> bool: ...

    def create_job(self, *, user_id: str, job_type: str, payload: dict[str, Any]) -> dict[str, Any]: ...

    def claim_next_job(self, *, job_types: list[str] | None = None) -> dict[str, Any] | None: ...

    def update_job(self, *, user_id: str, job_id: str, updates: dict[str, Any]) -> None: ...

    def add_stage_run(self, *, job_id: str, stage: str, status: str, duration_ms: int, details: dict[str, Any]) -> None: ...

    def get_job(self, *, user_id: str, job_id: str) -> dict[str, Any] | None: ...

    def list_stage_runs(self, *, job_id: str) -> list[dict[str, Any]]: ...
